<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \GhostUnicorns\Ga4\ViewModel\GenericLayer $viewModel */
$viewModel = $block->getData('view_model');
?>

<!-- GA4 Generic Layer (before the ga4 init) - START -->
<script>
    window.dataLayer = window.dataLayer || [];
    const genericLayer = {
        'login_status': '<?= $viewModel->getLoginStatus() ?>',
        'page_type': '<?= $viewModel->getPageType() ?>',
        'site_area': '<?= $viewModel->getSiteArea() ?>',
        'ecommerce_area': '<?= $viewModel->getEcommerceArea() ?>',
        'page_language': '<?= $viewModel->getLanguage() ?>',
    };
    <?php if ($userEmailMd5 = $viewModel->getUserEmailMd5()): ?>
    genericLayer['user_email_md5'] = '<?= $userEmailMd5  ?>';
    <?php endif; ?>
    <?php if ($userEmailSha256 = $viewModel->getUserEmailSha256()): ?>
    genericLayer['user_email_sha256'] = '<?= $userEmailSha256  ?>';
    <?php endif; ?>
    window.dataLayer.push(genericLayer);
</script>
<!-- GA4 Generic Layer (before the ga4 init) - END -->
