<?php
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
/** @var \Magento\GoogleTagManager\Block\ListJson $block */
/** @var $escaper \Magento\Framework\Escaper */

/** @var \GhostUnicorns\Ga4\ViewModel\ProductList $viewModel */
$viewModel = $block->getViewModel();

$productCollection = $block->getLoadedProductCollection();
$block->checkCartItems();
?>

<?php if ($productCollection && count($productCollection) > 0) { ?>
    <?php
    $listPosition = 0;
    if (is_object($productCollection) && $productCollection->getCurPage() > 0) {
        $position = ($productCollection->getCurPage() - 1) * $productCollection->getPageSize() + 1;
    } else {
        $position = 1;
    }

    $blockName = $block->escapeJs($block->getBlockName());

    $scriptString = <<<script
        var staticImpressions = staticImpressions || {};
        staticImpressions['{$blockName}'] = [
script;

    foreach ($productCollection as $product) {
        $listName = $escaper->escapeJs($block->getCurrentListName());
        $product = $viewModel->getProductLayerInList($product->getSku(), (string)$position, $listName, (string)$listPosition);
        $scriptString .= $product;
        $position++;
        $listPosition++;
    }
    $scriptString .= '];';
    ?>
    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false); ?>
    <?php
}
