<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>

<!-- GA4 Mini cart Layer - START -->
<script>
    require([
        'jquery',
        'GhostUnicorns_Ga4/js/actions/open-minicart',
        'domReady!'
    ], function ($, openMinicart) {
        const miniCart = $('[data-block=\'minicart\']');
        miniCart.on('dropdowndialogopen', openMinicart);
    });
</script>
<!-- GA4 Mini cart Layer - END -->
